- name: Cria configuração NGINX para o backend
  copy:
    dest: /etc/nginx/sites-available/{{ nginx_backend_site_name }}
    content: |
      server {
        listen 80;
        server_name {{ backend_domain }};
        return 301 https://$host$request_uri;
      }

      server {
        listen 443 ssl;
        server_name {{ backend_domain }};

        ssl_certificate /etc/letsencrypt/live/{{ backend_domain }}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/{{ backend_domain }}/privkey.pem;

        location / {
          proxy_pass http://{{ api_host }}:{{ api_port }};
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
      }

- name: Ativa site NGINX do backend
  file:
    src: /etc/nginx/sites-available/{{ nginx_backend_site_name }}
    dest: /etc/nginx/sites-enabled/{{ nginx_backend_site_name }}
    state: link
    force: yes

- name: Remove default site do NGINX (se existir)
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
    force: yes

- name: Valida configuração do NGINX
  command: nginx -t
  register: nginx_test_result
  changed_when: false
  failed_when: nginx_test_result.rc != 0

- name: Reinicia o NGINX
  service:
    name: nginx
    state: restarted
    enabled: true
