# Instalação do node.js
- name: Adiciona a chave GPG do NodeSource
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Adiciona o repositório NodeSource do Node.js {{ node_version }}
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x jammy main" # jammy é a versão do Ubuntu 22.04, substituir por {{ ansible_distribution_release }}
    state: present
    filename: "nodesource"

- name: Atualiza o cache do APT
  apt:
    update_cache: yes

- name: Instala Node.js
  apt:
    name: nodejs
    state: present

# Instala o gerenciador de processos PM2 globalmente
- name: Instala PM2 globalmente
  npm:
    name: pm2
    global: yes
    executable: npm
