- name: Instala Certbot
  apt:
    name:
      - certbot
      - python3-certbot
    state: present
    update_cache: yes

- name: Para o NGINX temporariamente para liberar porta 80
  service:
    name: nginx
    state: stopped

- name: Cria certificados SSL para o backend
  command: >
    certbot certonly --standalone --non-interactive --agree-tos
    --email {{ certbot_email }}
    --domains {{ backend_domain }}
  notify: Reinicia o NGINX

- name: Cria certificados SSL para o frontend
  command: >
    certbot certonly --standalone --non-interactive --agree-tos
    --email {{ certbot_email }}
    --domains {{ frontend_domain }}
  notify: Reinicia o NGINX

- name: Agendar renovação automática dos certificados
  cron:
    name: "Renovar certificados SSL diariamente"
    job: "certbot renew --quiet"
    special_time: daily
